"""venue table

Revision ID: 454d2b68bd3a
Revises: 407cdba08c65
Create Date: 2025-09-22 14:12:30.022590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454d2b68bd3a'
down_revision = '407cdba08c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('picture')

    op.drop_table('venues')
    # ### end Alembic commands ###
