"""relationships

Revision ID: df8c1bccbeaa
Revises: e7a3e34f8ad1
Create Date: 2025-09-22 14:41:05.676236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8c1bccbeaa'
down_revision = 'e7a3e34f8ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_rsvps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['organizer_id'], ['id'])
        batch_op.create_foreign_key(None, 'venues', ['venue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organizer_id')
        batch_op.drop_column('venue_id')

    with op.batch_alter_table('event_rsvps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
