"""events rsvp table

Revision ID: e7a3e34f8ad1
Revises: 454d2b68bd3a
Create Date: 2025-09-22 14:18:32.343831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a3e34f8ad1'
down_revision = '454d2b68bd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dietary_preference', sa.String(), nullable=False),
    sa.Column('special_request', sa.String(), nullable=False),
    sa.Column('rsvp_status', sa.String(), nullable=False),
    sa.Column('rsvp_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_rsvps')
    # ### end Alembic commands ###
